import assert from 'node:assert/strict';
import { Selection } from '../client/js/selection.js';
import { Room } from '../server/room.js';
import { Phase } from '../shared/const.js';
const selection = new Selection();
selection.set(Array.from({length: 20}, (_, i) => i));
assert.equal(selection.ids.length, 12);
selection.set([1, 1, 2]); selection.toggle(1); selection.toggle(3);
assert.deepEqual(selection.ids, [2, 3]);
selection.assign('1', id => id !== 3); selection.set([]);
selection.recall('1', () => true); assert.deepEqual(selection.ids, [2]);
selection.recall('1', () => false); assert.deepEqual(selection.ids, []);
selection.recall('9', () => true); assert.deepEqual(selection.ids, []);
const entities = new Map([[1,{u:'hero',k:1}],[2,{u:'footman',k:2}],[3,{u:'footman',k:2}],[4,{u:'archer',k:2}]]);
selection.set([1,2,3,4]);
assert.deepEqual(selection.subgroups(entities),[[1],[2,3],[4]]);
selection.cycle(entities); assert.equal(selection.activeId,2);
assert.deepEqual(selection.ids,[1,2,3,4],'subgroup cycling preserves whole selection');
selection.cycle(entities); assert.equal(selection.activeId,4);
selection.cycle(entities); assert.equal(selection.activeId,1,'cycle wraps');
selection.cycle(entities,-1); assert.equal(selection.activeId,4,'reverse cycle wraps');
selection.prune(id=>id!==4); assert.ok(selection.ids.includes(selection.activeId),'removed primary falls back to a selected unit');
selection.set([]); selection.cycle(entities); assert.equal(selection.activeId,null);
const units = new Map(Array.from({length: 20}, (_, i) => [i + 1, { id: i + 1, playerIndex: 0, alive: true }]));
Object.assign(units.get(2), { playerIndex: 1 }); // allies are not owned
Object.assign(units.get(3), { alive: false });
Object.assign(units.get(4), { hidden: true });
Object.assign(units.get(5), { locust: true });
const orders = [];
const room = Object.create(Room.prototype);
room.phase = Phase.PLAYING;
room.world = { units, isLocust: u => u.locust, order: (u,o) => { orders.push([u.id,o]); return true; }, target: id => units.get(id), hostile: (u,t) => u.playerIndex !== t.playerIndex };
const p = { entId: 1, slot: 0 };
const command = m => { orders.length = 0; room.command(p,m); return orders.map(([id]) => id); };
assert.deepEqual(command({t:'move', x:10, y:20, unitIds:[1,1,2,3,4,5,6,'7',999]}), [1,6]);
assert.equal(units.get(6).controlled, true);
assert.deepEqual(command({t:'stop'}), [1]);
for (const unitIds of [[], null, {}, [2,3,4,5]]) assert.deepEqual(command({t:'stop',unitIds}), []);
assert.deepEqual(command({t:'move',x:NaN,y:10,unitIds:[1]}), []);
assert.deepEqual(command({t:'hold',unitIds:Array.from({length:20},(_,i)=>i+1)}), [1,6,7,8,9,10,11,12]);
units.get(1).alive = false;
assert.deepEqual(command({t:'hold',unitIds:[1,6]}), [6]);
assert.deepEqual(command({t:'attack',targetId:2,unitIds:[6,7]}), [6,7]);
assert.equal(orders[0][1].target, units.get(2));
room.phase = 'lobby'; assert.deepEqual(command({t:'stop',unitIds:[6]}), []);
console.log('Selection and command ownership checks passed');
